// This file was autogenerated by depswriter.py.
// Please do not edit.
goog.addDependency('../../../../src/vs/models/base.js', ['vs.models'], [], false);
goog.addDependency('../../../../src/vs/models/plugins/__namespace__.js', ['vs.models.plugins'], ['vs.models.plugins.BigwigDataSource'], false);
goog.addDependency('../../../../src/vs/models/plugins/bigwig-data-source.js', ['vs.models.plugins.BigwigDataSource'], ['vs.models'], false);
